name: DP Run Tests
on:
  push:
jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nationalarchives/tdr-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/tdr-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository sbt-assembly-log4j"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Run tests
        run: sbt test scripted scalafmtCheckAll
